# https://pre-commit.com/
ci:
  autoupdate_schedule: monthly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: 'csv'
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.5.6"
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]

      # Run the formatter.
      - id: ruff-format


  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-mypy
        args: ["--ignore-missing-imports"]
      - id: nbqa-ruff
        args: ["--fix"]
      - id: nbqa-isort
        args: ["--profile=black"]
        additional_dependencies: [isort==5.6.4]
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: ["--py39-plus"]
